### ISSUE TITLE
requirements.txt installs packages that are too new and do not work

### ISSUE THREAD

**Issue by simo-tuomisto** [google-research/slot-attention-video#2]
I tried replicating the training using the included installation instructions, but found that the requirements.txt is outdated in multiple places.

I created a conda-environment with the following environment.yml:
```yml
name: slot-attention-orig
channels:
  - conda-forge
dependencies:
  - cudatoolkit>=11.2
  - cudnn=8.2
  - pip
  - pip:
    - -f https://storage.googleapis.com/jax-releases/jax_releases.html
    - jax[cuda]>=0.3.2
    - absl-py>=0.12.0
    - numpy>=1.21.5
    - tensorflow-cpu>=2.7.0  # Using tensorflow-cpu to have all GPU memory for JAX.
    - tensorflow-datasets>=4.4.0
    - matplotlib>=3.5.0
    - clu>=0.0.3
    - flax>=0.3.5
    - chex>=0.0.7
    - optax==0.1.0
    - ml-collections==0.1.0
    - scikit-image
```
Installation with this environment will fail as [Jax has changed the  release location for CUDA-enabled binaries](https://github.com/google/jax#pip-installation-gpu-cuda). Thus this will only install if one changes:
```diff
-    - -f https://storage.googleapis.com/jax-releases/jax_releases.html
+    - -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```
However, this environment will not work and will crash before the training starts with the following errors:
```txt
Traceback (most recent call last):
  File "GIT_DIR/slot-attention-video/savi/main.py", line 63, in <module>
    app.run(main)
  File "ENV_DIR/lib/python3.10/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "ENV_DIR/lib/python3.10/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "GIT_DIR/slot-attention-video/savi/main.py", line 59, in main
    trainer.train_and_evaluate(FLAGS.config, FLAGS.workdir)
  File "GIT_DIR/slot-attention-video/savi/lib/trainer.py", line 202, in train_and_evaluate
    state_vars, initial_params = init_model(rng)
  File "GIT_DIR/slot-attention-video/savi/lib/trainer.py", line 188, in init_model
    initial_vars = model.init(
  File "ENV_DIR/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "ENV_DIR/lib/python3.10/site-packages/flax/linen/module.py", line 1230, in init
    _, v_out = self.init_with_output(
  File "ENV_DIR/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "ENV_DIR/lib/python3.10/site-packages/flax/linen/module.py", line 1197, in init_with_output
    return self.apply(
  File "ENV_DIR/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "ENV_DIR/lib/python3.10/site-packages/flax/linen/module.py", line 1162, in apply
    return apply(
  File "ENV_DIR/lib/python3.10/site-packages/flax/core/scope.py", line 806, in wrapper
    y = fn(root, *args, **kwargs)
  File "ENV_DIR/lib/python3.10/site-packages/flax/linen/module.py", line 1446, in scope_fn
    return fn(module.clone(parent=scope), *args, **kwargs)
  File "ENV_DIR/lib/python3.10/site-packages/flax/linen/transforms.py", line 1166, in wrapped_fn
    return prewrapped_fn(self, *args, **kwargs)
  File "ENV_DIR/lib/python3.10/site-packages/flax/linen/module.py", line 350, in wrapped_module_method
    return self._call_wrapped_method(fun, args, kwargs)
  File "ENV_DIR/lib/python3.10/site-packages/flax/linen/module.py", line 657, in _call_wrapped_method
    y = fun(self, *args, **kwargs)
  File "GIT_DIR/slot-attention-video/savi/modules/video.py", line 136, in __call__
    _, states = processor(init_state, encoded_inputs, padding_mask, train)
  File "ENV_DIR/lib/python3.10/site-packages/flax/linen/transforms.py", line 1166, in wrapped_fn
    return prewrapped_fn(self, *args, **kwargs)
  File "ENV_DIR/lib/python3.10/site-packages/flax/linen/transforms.py", line 372, in wrapped_fn
    return trafo_fn(module_scopes, *args, **kwargs)
  File "ENV_DIR/lib/python3.10/site-packages/flax/core/lift.py", line 218, in wrapper
    y, out_variable_groups_xs_t = fn(
  File "ENV_DIR/lib/python3.10/site-packages/flax/core/lift.py", line 766, in inner
    broadcast_vars, (carry_vars, c), (ys, scan_vars) = scanned(
  File "ENV_DIR/lib/python3.10/site-packages/flax/core/axes_scan.py", line 135, in scan_fn
    _, out_pvals, _ = pe.trace_to_jaxpr(f_flat, in_pvals)
  File "ENV_DIR/lib/python3.10/site-packages/jax/_src/profiler.py", line 312, in wrapper
    return func(*args, **kwargs)
  File "ENV_DIR/lib/python3.10/site-packages/jax/interpreters/partial_eval.py", line 607, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "ENV_DIR/lib/python3.10/site-packages/jax/linear_util.py", line 183, in call_wrapped
    ans = gen.send(ans)
  File "ENV_DIR/lib/python3.10/site-packages/jax/interpreters/partial_eval.py", line 2258, in trace_to_subjaxpr
    jaxpr, consts, env = tracers_to_jaxpr(in_tracers, out_tracers)
  File "ENV_DIR/lib/python3.10/site-packages/jax/interpreters/partial_eval.py", line 785, in tracers_to_jaxpr
    assert False
jax._src.traceback_util.UnfilteredStackTrace: AssertionError

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ENV_DIR/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "ENV_DIR/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "GIT_DIR/slot-attention-video/savi/main.py", line 63, in <module>
    app.run(main)
  File "ENV_DIR/lib/python3.10/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "ENV_DIR/lib/python3.10/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "GIT_DIR/slot-attention-video/savi/main.py", line 59, in main
    trainer.train_and_evaluate(FLAGS.config, FLAGS.workdir)
  File "GIT_DIR/slot-attention-video/savi/lib/trainer.py", line 202, in train_and_evaluate
    state_vars, initial_params = init_model(rng)
  File "GIT_DIR/slot-attention-video/savi/lib/trainer.py", line 188, in init_model
    initial_vars = model.init(
  File "GIT_DIR/slot-attention-video/savi/modules/video.py", line 136, in __call__
    _, states = processor(init_state, encoded_inputs, padding_mask, train)
  File "ENV_DIR/lib/python3.10/site-packages/flax/core/axes_scan.py", line 135, in scan_fn
    _, out_pvals, _ = pe.trace_to_jaxpr(f_flat, in_pvals)
AssertionError
```
In the output I've replaced the path to the conda environment with `ENV_DIR` and path to the git repository with `GIT_DIR`.

These errors occur because [flax has done multiple breaking changes since 0.3.5](https://github.com/google/flax/blob/main/CHANGELOG.md). Locking flax version is not enough as newer versions of jax do not work with older version of flax (specifically, one will encounter [this issue with import of `jax._src.numpy.lax_numpy`](https://stackoverflow.com/a/72113173)).

By doing the following changes, one will get a working environment:
```diff
-    - jax[cuda]>=0.3.2
+    - jax[cuda]==0.3.2
-    - flax>=0.3.5
+    - flax==0.3.5
```

In the end a working environment file will look like this:
```env
  name: slot-attention-versions-locked
  channels:
    - conda-forge
  dependencies:
    - cudatoolkit>=11.2
    - cudnn=8.2
    - pip
    - pip:
      - -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
      - jax[cuda]==0.3.2
      - absl-py>=0.12.0
      - numpy>=1.21.5
      - tensorflow-cpu>=2.7.0
      - tensorflow-datasets>=4.4.0
      - matplotlib>=3.5.0
      - clu>=0.0.3
      - flax==0.3.5
      - chex>=0.0.7
      - optax==0.1.0
      - ml-collections==0.1.0
      - scikit-image
```

Can you update the requirements.txt to include the changes?

You can also include the environment file if you want.

**Comment by tkipf** [comment]
Thanks a lot for bringing this to our attention! I have updated `requirements.txt` to use an older version of JAX/Flax (and related dependencies), which should hopefully allow you to use the codebase "as is" now. We will soon update the code base to be compatible with later versions of JAX/Flax.
